
CREATE TABLE `DWD_CLAIM_COUNT_DAY` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '保险公司渠道',
    `GMT_CREATED` DATE COMMENT '创建时间',
    `JJL` BIGINT COMMENT '进件量',
    `CANCEL_VOL` BIGINT COMMENT '撤销件数',
    `XXQD` BIGINT COMMENT '线上渠道',
    `XSQD` BIGINT COMMENT '线下渠道',
    `LRL` BIGINT  COMMENT '录入量',
    `DRHCAL` BIGINT COMMENT '当日回传案件量',
    `BLCHCAL` BIGINT COMMENT '半流程回传案件量',
    `QLCHCAL` BIGINT COMMENT '全流程回传案件量',
    `PERC_ALL_FLOW` DECIMAL(10,4) COMMENT '全流程占比',
    `HCSBAL` BIGINT COMMENT '回传失败案件量',
    `ZDSHAL` BIGINT COMMENT '自动审核案件数(回传)',
    `ZDSHAL_RW` BIGINT COMMENT '自动审核案件数(任务)',
    `SHZDHL` DECIMAL(10,4) COMMENT '审核自动化率(回传)',
    `SHZDHL_RW` DECIMAL(10,4) COMMENT '审核自动化率(任务)',
    `FH_AUTO_CLAIM_COUNT` BIGINT COMMENT '复核自动案件数',
    `FHZDHL` DECIMAL(10,4) COMMENT '复核自动化率',
    `QUESTION_CLAIM_VOL` BIGINT COMMENT '问题件案件数',
    `HOSPATAL_CLAIM_VOL` BIGINT COMMENT '住院案件数',
    `DATA_DT` VARCHAR(20) COMMENT '数据日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='日案件量报表';




CREATE TABLE `DWD_OUT_HOSPITAL_SUMMARY_DF` (
  `C_APP_NO` varchar(50) COMMENT '申请号',
  `url` varchar(50) COMMENT '图片地址',
  `text` varchar(500) COMMENT '识别文本信息'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='出院小结表';


drop table if exists `CLAIM_DWD`.`DWD_PERSON_WORK_VOL`;

CREATE TABLE CLAIM_DWD.DWD_PERSON_WORK_VOL (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
    `COMM_TIME` DATE  COMMENT '日期',
    `FULL_NAME` VARCHAR(40)  COMMENT '姓名',
    `PRE_AUDIT_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '预审案件数',
    `HOSTIPAL_MATCH_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '医院匹配条数',
    `DIAG_MATCH_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '诊断匹配条数',
    `DETAIL_MATCH_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '明细匹配条数',
    `CHARG_CLAIM_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '扣费案件数',
    `CHARG_BILL_VOL` BIGINT  NOT NULL DEFAULT 0 COMMENT '扣费发票数',
    `CONFIG_CLAIM_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '配置案件数',
    `AUDIT_CLAIM_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '审核案件数',
    `FH_CLAIM_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '复核案件数',
    `ZDGZ_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '诊断规则数',
    `HOS_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '医院条',
    `MED_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '药品条',
    `TREAT_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '诊疗条',
    `MATE_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '材料条',
    `MED_INS_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '医保比例条',
    `cancel_NUM` BIGINT  NOT NULL DEFAULT 0 COMMENT '撤案量',
    `DATA_DT` VARCHAR(20)  COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='业务员工时报表';

drop table if exists `CLAIM_DWD`.`DWD_EXAM_AUTO_POLICY`;

CREATE TABLE `CLAIM_DWD`.`DWD_EXAM_AUTO_POLICY` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `COMM_DATE` DATE NOT NULL COMMENT '时间',
  `POLICY_NO` VARCHAR(80) NOT NULL COMMENT '保单号',
  `IS_POLICY_AUTO` VARCHAR(20)  COMMENT '是否开启保单自动化',
  `AUTO_EXAM_VOL` bigint  NOT NULL DEFAULT 0  COMMENT '自动审核案件量',
  `ALL_FLOW_HCVOL` bigint  NOT NULL DEFAULT 0  COMMENT '全部审核案件量',
  `POLICY_CRT_TM` DATETIME NOT NULL COMMENT '保单创建时间',
  `EARLY_CLAIM_DATE` VARCHAR(20) COMMENT '最早案件时间',
  `NEAR_CLAIM_DATE` VARCHAR(20) COMMENT '最近案件时间',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='保单审核自动化率表';


CREATE TABLE `CLAIM_DWD`.`ALL_FLOW_EFF_MONITOR_DWD` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `IN_CLAIM` INT(10) COMMENT '案件录入量',
  `PER_MANUAL_CLAIM_VOL` INT(10) COMMENT '预审人工案件数',
  `HOSPITAL_MANUAL_VOL` INT(10) COMMENT '医院人工匹配量',
  `HOSPITAL_MATCH_TOTAL` INT(10) COMMENT '医院匹配总量',
  `DIAG_MATCH_MANUAL_VOL` INT(10) COMMENT '诊断匹配人工数量',
  `DIAG_MATCH_TOTAL` INT(10) COMMENT '诊断匹配全量',
  `DETAIL_MANUAL_MATCH_VOL` INT(10) COMMENT '明细人工匹配量',
  `DETAIL_TOTAL` INT(10) COMMENT '明细总数量',
  `MANUAL_CHARGE_BILL_VOL` INT(10) COMMENT '人工扣费发票量',
  `MANUAL_CHARGE_VOL` INT(10) COMMENT '人工扣费案件量',
  `CHARGE_TATAL` INT(10) COMMENT '扣费总量',
  `CONFIG_MANUAL_VOL` INT(10) COMMENT '配置人工数',
  `CONFIG_TOTAL` INT(10) COMMENT '配置总数',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件全流程数量';




CREATE TABLE `CLAIM_DWD`.`ALL_FLOW_TBC_MONITOR_DWD` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `IN_CLAIM` INT(10) COMMENT '案件录入量',
  `PER_MANUAL_CLAIM_VOL` INT(10) COMMENT '预审人工案件数',
  `HOSPITAL_MANUAL_VOL` INT(10) COMMENT '医院人工匹配量',
  `HOSPITAL_MATCH_TOTAL` INT(10) COMMENT '医院匹配总量',
  `DIAG_MATCH_MANUAL_VOL` INT(10) COMMENT '诊断匹配人工数量',
  `DIAG_MATCH_TOTAL` INT(10) COMMENT '诊断匹配全量',
  `DETAIL_MANUAL_MATCH_VOL` INT(10) COMMENT '明细人工匹配量',
  `DETAIL_TOTAL` INT(10) COMMENT '明细总数量',
  `MANUAL_CHARGE_BILL_VOL` INT(10) COMMENT '人工扣费发票量',
  `MANUAL_CHARGE_VOL` INT(10) COMMENT '人工扣费案件量',
  `CHARGE_TATAL` INT(10) COMMENT '扣费总量',
  `CONFIG_MANUAL_VOL` INT(10) COMMENT '配置人工数',
  `CONFIG_TOTAL` INT(10) COMMENT '配置总数',
  `SHZDHL_RW` DECIMAL(10, 4) COMMENT '审核自动化率(任务)',
  `SH_AUTO_RATE` DECIMAL(10, 4) COMMENT '审核自动化率(任务)',
  `FH_AUTO_RATE` DECIMAL(10, 4) COMMENT '复核自动化率',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='太保财全渠道案件全流程数量';


CREATE TABLE `CLAIM_DWD`.`ALL_FLOW_TK_MONITOR_DWD` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
    `CREATE_TIME` DATE COMMENT '时间',
    `IN_CLAIM` INT COMMENT '案件录入量',
    `PER_MANUAL_CLAIM_VOL` INT COMMENT '预审人工案件数',
    `HOSPITAL_MANUAL_VOL` INT COMMENT '医院人工匹配量',
    `HOSPITAL_MATCH_TOTAL` INT COMMENT '医院匹配总量',
    `DIAG_MATCH_MANUAL_VOL` INT COMMENT '诊断匹配人工数量',
    `DIAG_MATCH_TOTAL` INT COMMENT '诊断匹配全量',
    `DETAIL_MANUAL_MATCH_VOL` INT COMMENT '明细人工匹配量',
    `DETAIL_TOTAL` INT COMMENT '明细总数量',
    `MANUAL_CHARGE_BILL_VOL` INT COMMENT '人工扣费发票量',
    `MANUAL_CHARGE_VOL` INT COMMENT '人工扣费案件量',
    `CHARGE_TATAL` INT COMMENT '扣费总量',
    `CONFIG_MANUAL_VOL` INT COMMENT '配置人工数',
    `CONFIG_TOTAL` INT COMMENT '配置总数',
    `SHZDHL_RW` DECIMAL(10, 4) COMMENT '审核自动化率(任务)',
    `SH_AUTO_RATE` DECIMAL(10, 4) COMMENT '审核自动化率(任务)',
    `FH_AUTO_RATE` DECIMAL(10, 4) COMMENT '复核自动化率',
    `DATA_DT` VARCHAR(10) COMMENT '调度日期'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='泰康全渠道案件全流程数量';



CREATE TABLE claim_dwd.`DWD_ALL_FLOW_EFF_MONITOR` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
    `CREATE_TIME` DATE COMMENT '时间',
    `IN_CLAIM` BIGINT COMMENT '案件录入量',
    `PER_MANUAL_CLAIM_VOL` BIGINT COMMENT '预审人工案件数',
    `HOSPITAL_MANUAL_VOL` BIGINT COMMENT '医院人工匹配量',
    `HOSPITAL_MATCH_TOTAL` BIGINT COMMENT '医院匹配总量',
    `DIAG_MATCH_MANUAL_VOL` BIGINT COMMENT '诊断匹配人工数量',
    `DIAG_MATCH_TOTAL` BIGINT COMMENT '诊断匹配全量',
    `DETAIL_MANUAL_MATCH_VOL` BIGINT COMMENT '明细人工匹配量',
    `DETAIL_TOTAL` BIGINT COMMENT '明细总数量',
    `MANUAL_CHARGE_BILL_VOL` BIGINT COMMENT '人工扣费发票量',
    `MANUAL_CHARGE_VOL` BIGINT COMMENT '人工扣费案件量',
    `CHARGE_TOTAL` BIGINT COMMENT '扣费总量',
    `CONFIG_MANUAL_VOL` BIGINT COMMENT '配置人工数',
    `CONFIG_TOTAL` BIGINT COMMENT '配置总数',
    `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='全流程效率监控表';




CREATE TABLE claim_dwd.`DWD_ALL_FLOW_TK_MONITOR` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
    `CREATE_TIME` DATE COMMENT '时间',
    `IN_CLAIM` BIGINT COMMENT '案件录入量',
    `PER_MANUAL_CLAIM_VOL` BIGINT COMMENT '预审人工案件数',
    `HOSPITAL_MANUAL_VOL` BIGINT COMMENT '医院人工匹配量',
    `HOSPITAL_MATCH_TOTAL` BIGINT COMMENT '医院匹配总量',
    `DIAG_MATCH_MANUAL_VOL` BIGINT COMMENT '诊断匹配人工数量',
    `DIAG_MATCH_TOTAL` BIGINT COMMENT '诊断匹配全量',
    `DETAIL_MANUAL_MATCH_VOL` BIGINT COMMENT '明细人工匹配量',
    `DETAIL_TOTAL` BIGINT COMMENT '明细总数量',
    `MANUAL_CHARGE_BILL_VOL` BIGINT COMMENT '人工扣费发票量',
    `MANUAL_CHARGE_VOL` BIGINT COMMENT '人工扣费案件量',
    `CHARGE_TOTAL` BIGINT COMMENT '扣费总量',
    `CONFIG_MANUAL_VOL` BIGINT COMMENT '配置人工数',
    `CONFIG_TOTAL` BIGINT COMMENT '配置总数',
    `SHZDHL_RW` DECIMAL(10,4) COMMENT '审核自动化率(任务)',
    `SH_AUTO_RATE` DECIMAL(10,4) COMMENT '审核自动化率(回传)',
    `FH_AUTO_RATE` DECIMAL(10,4) COMMENT '复核自动化率',
    `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='泰康全流程效率监控表';


CREATE TABLE claim_dwd.`DWD_ALL_FLOW_TBC_MONITOR` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
    `CREATE_TIME` DATE COMMENT '时间',
    `IN_CLAIM` BIGINT  COMMENT '案件录入量',
    `PER_MANUAL_CLAIM_VOL` BIGINT COMMENT '预审人工案件数',
    `HOSPITAL_MANUAL_VOL` BIGINT COMMENT '医院人工匹配量',
    `HOSPITAL_MATCH_TOTAL` BIGINT COMMENT '医院匹配总量',
    `DIAG_MATCH_MANUAL_VOL` BIGINT COMMENT '诊断匹配人工数量',
    `DIAG_MATCH_TOTAL` BIGINT COMMENT '诊断匹配全量',
    `DETAIL_MANUAL_MATCH_VOL` BIGINT COMMENT '明细人工匹配量',
    `DETAIL_TOTAL` BIGINT COMMENT '明细总数量',
    `MANUAL_CHARGE_BILL_VOL` BIGINT COMMENT '人工扣费发票量',
    `MANUAL_CHARGE_VOL` BIGINT COMMENT '人工扣费案件量',
    `CHARGE_TOTAL` BIGINT COMMENT '扣费总量',
    `CONFIG_MANUAL_VOL` BIGINT COMMENT '配置人工数',
    `CONFIG_TOTAL` BIGINT COMMENT '配置总数',
    `SHZDHL_RW` DECIMAL(10,4) COMMENT '审核自动化率(任务)',
    `SH_AUTO_RATE` DECIMAL(10,4) COMMENT '审核自动化率(回传)',
    `FH_AUTO_RATE` DECIMAL(10,4) COMMENT '复核自动化率',
    `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='太保财全流程效率监控表';


CREATE TABLE claim_dwd.`dwd_claim_risk_analysis_detail` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `channel_order` BIGINT NOT NULL COMMENT '排序',
  `case_status` VARCHAR(50) NOT NULL COMMENT '案件状态',
  `total_count` BIGINT NOT NULL COMMENT '总计',
  `distributed_count` BIGINT NOT NULL COMMENT '分配数',
  `pre_audit_count` BIGINT NOT NULL COMMENT '预审数',
  `match_count` BIGINT NOT NULL COMMENT '匹配数',
  `rule_match_count` BIGINT NOT NULL COMMENT '规则匹配数',
  `deduct_count` BIGINT NOT NULL COMMENT '扣费数',
  `auto_audit_count` BIGINT NOT NULL COMMENT '自动审核数',
  `audit_count` BIGINT NOT NULL COMMENT '审核数',
  `review_count` BIGINT NOT NULL COMMENT '复核数',
  `company_review_count` BIGINT NOT NULL COMMENT '保司复核数',
  `pending_count` BIGINT NOT NULL COMMENT '待处理数',
  `postback_count` BIGINT NOT NULL COMMENT '回传数',
  `entry_count` BIGINT NOT NULL COMMENT '录入数',
  `issue_count` BIGINT NOT NULL COMMENT '问题件数',
  `status_order` BIGINT NOT NULL COMMENT '状态排序',
  `channel_sort` BIGINT NOT NULL COMMENT '渠道排序'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='控制台风控分析明细表';


CREATE TABLE claim_dwd.`dwd_claim_risk_analysis_total` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道值',
  `pending_total` BIGINT NOT NULL COMMENT '待处理总数',
  `pending_today` BIGINT NOT NULL COMMENT '今日待处理数',
  `warning` BIGINT NOT NULL COMMENT '预警数',
  `overdue` BIGINT NOT NULL COMMENT '超时数',
  `daily_intake` BIGINT NOT NULL COMMENT '当天进件量',
  `daily_completion` BIGINT NOT NULL COMMENT '当天完成量'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='控制台风控分析汇总表';

drop table if exists claim_dwd.DWD_EXAM_RISK_ANALYSIS_POLICY;

CREATE TABLE CLAIM_DWD.DWD_EXAM_RISK_ANALYSIS_POLICY (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `GROUP_POLICY_NO` VARCHAR(50) COMMENT '保单号',
  `COMM_DATE` VARCHAR(50)   COMMENT '时间',
  `RISK_LAYER` VARCHAR(10) COMMENT '风控层次',
  `C_RISK_REASON` VARCHAR(1000) COMMENT '风控原因',
  `EXPLAIN_CODE` VARCHAR(1000) COMMENT '原因解释码',
  `EXPLAIN_DESC` VARCHAR(1000) COMMENT '原因解释',
  `TRIGGER_CLAIM_NUM` BIGINT  COMMENT '触发案件数',
  `CLAIM_NO` VARCHAR(30) COMMENT '申请号',
  product_type  VARCHAR(30) COMMENT '类型',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='风控分析详细数据表';




CREATE TABLE `CLAIM_DWD`.`DWD_GN_INPUT_FEE_COUNT` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(20) NOT NULL COMMENT '年月',
  `MZ_ONLINE_JLS` BIGINT DEFAULT NULL COMMENT '线上门诊发票结算记录数',
  `MZ_ONLINE_AJ` BIGINT DEFAULT NULL COMMENT '线上门诊发票案件数',
  `MZ_ONLINE_DJ` DECIMAL(10,2) DEFAULT NULL COMMENT '线上门诊发票数单价',
  `MZ_ONLINE_PRICE` DECIMAL(10,2) DEFAULT NULL COMMENT '线上门诊发票应付金额',
  `ZY_ONLINE_JLS` BIGINT DEFAULT NULL COMMENT '线上住院案件结算记录数',
  `ZY_ONLINE_AJ` BIGINT DEFAULT NULL COMMENT '线上住院案件数',
  `ZY_ONLINE_DJ` DECIMAL(10,2) DEFAULT NULL COMMENT '线上住院案件单价',
  `ZY_ONLINE_PRICE` DECIMAL(10,2) DEFAULT NULL COMMENT '线上住院案件应付金额',
  `PRICE_COUNT` DECIMAL(10,2) DEFAULT NULL COMMENT '费用合计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='广纳录入费用统计';



CREATE TABLE `CLAIM_DWD`.`DWD_SH_INPUT_FEE_COUNT` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(20) NOT NULL COMMENT '年月',
  `HOSPITAL_CLAIM_COUNT` BIGINT  DEFAULT 0 COMMENT '住院案件数',
  `HOSPITAL_JSJL_COUNT` BIGINT DEFAULT NULL COMMENT '住院结算记录数',
  `HOSPITAL_PRICE` DECIMAL(10,2) DEFAULT NULL COMMENT '住院单价',
  `HOSPITAL_FEE` DECIMAL(10,2) DEFAULT NULL COMMENT '住院应付金额',
  `MZ_ONLINE_CLAIM_COUNT` BIGINT  DEFAULT NULL COMMENT '门诊线上案件数',
  `MZ_ONLINE_JSJL_COUNT` BIGINT DEFAULT NULL COMMENT '门诊线上结算记录数',
  `MZ_ONLINE_PRICE` DECIMAL(10,2) DEFAULT NULL COMMENT '门诊线上单价',
  `MZ_ONLINE_FEE` DECIMAL(10,2) DEFAULT NULL COMMENT '门诊线上应付金额',
  `MZ_OFFLINE_CLAIM_COUNT` BIGINT  DEFAULT NULL COMMENT '门诊线下案件数',
  `MZ_OFFLINE_JSJL_COUNT` BIGINT DEFAULT NULL COMMENT '门诊线下结算记录数',
  `MZ_OFFLINE_PRICE` DECIMAL(10,2) DEFAULT NULL COMMENT '门诊线下单价',
  `MZ_OFFLINE_FEE` DECIMAL(10,2) DEFAULT NULL COMMENT '门诊线下应付金额',
  `TOTAL_FEE` DECIMAL(10,2) DEFAULT NULL COMMENT '费用合计',
  `DATA_DT` VARCHAR(20) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='施博录入费用统计';



CREATE TABLE `CLAIM_DWD`.`DWD_ZZ_INPUT_FEE_COUNT` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(20) NOT NULL COMMENT '年月',
  `MZ_ONLINE_JLS` bigint  DEFAULT NULL COMMENT '线下门诊发票结算记录数',
  `MZ_ONLINE_AJ` bigint  DEFAULT NULL COMMENT '线下门诊发票案件数',
  `MZ_ONLINE_DJ` DECIMAL(10,2) DEFAULT NULL COMMENT '线下门诊发票数单价',
  `MZ_ONLINE_PRICE` DECIMAL(10,2) DEFAULT NULL COMMENT '线下门诊发票应付金额',
  `ZY_ONLINE_JLS` bigint DEFAULT NULL COMMENT '线下住院案件结算记录数',
  `ZY_ONLINE_AJ` bigint  DEFAULT NULL COMMENT '线下住院案件数',
  `ZY_ONLINE_DJ` DECIMAL(10,2) DEFAULT NULL COMMENT '线下住院案件单价',
  `ZY_ONLINE_PRICE` DECIMAL(10,2) DEFAULT NULL COMMENT '线下住院案件应付金额',
  `PRICE_COUNT` DECIMAL(10,2) DEFAULT NULL COMMENT '费用合计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='智在录入费用统计';


CREATE TABLE `CLAIM_DWD`.`DWD_CDSJ_INPUT_FEE_COUNT` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
    `YEAR_MONTH` VARCHAR(20) NOT NULL COMMENT '年月',
    `MZ_ONLINE_JLS` bigint DEFAULT NULL COMMENT '线上门诊发票结算记录数',
    `MZ_ONLINE_AJ` bigint  DEFAULT NULL COMMENT '线上门诊发票案件数',
    `MZ_ONLINE_DJ` DECIMAL(10, 2) DEFAULT NULL COMMENT '线上门诊发票数单价',
    `MZ_ONLINE_PRICE` DECIMAL(10, 2) DEFAULT NULL COMMENT '线上门诊发票应付金额',
    `ZY_ONLINE_JLS` bigint DEFAULT NULL COMMENT '线上住院案件结算记录数',
    `ZY_ONLINE_AJ` bigint DEFAULT NULL COMMENT '线上住院案件数',
    `ZY_ONLINE_DJ` DECIMAL(10, 2) DEFAULT NULL COMMENT '线上住院案件单价',
    `ZY_ONLINE_PRICE` DECIMAL(10, 2) DEFAULT NULL COMMENT '线上住院案件应付金额',
    `PRICE_COUNT` DECIMAL(10, 2) DEFAULT NULL COMMENT '费用合计',
    `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='成都视觉录入费用统计';


drop table if exists  `CLAIM_DWD`.`DWD_ZA01_BILL_DETAIL`;

CREATE TABLE `CLAIM_DWD`.`DWD_ZA01_BILL_DETAIL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
    `COMM_DATE` DATE NOT NULL COMMENT '日期',
    `ACCEPT_NUM` VARCHAR(30) NOT NULL COMMENT '受理编号',
    `POLICY_TYPE` VARCHAR(20)  COMMENT '保单类型',
    `ACCEPT_DATE` DATE NOT NULL COMMENT '受理时间',
    `BACK_DATE` DATE COMMENT '回传时间',
    `DIAG_TYPE` VARCHAR(20)  COMMENT '就诊类型',
    `DIAG_VOL` BIGINT  COMMENT '就诊次数',
    `BILL_VOL` BIGINT  COMMENT '账单数',
    `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='暖哇对账明细';

drop table if exists  `CLAIM_DWD`.`DWD_ZA01_BILL_TOTAL`;

CREATE TABLE `CLAIM_DWD`.`DWD_ZA01_BILL_TOTAL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(100) NOT NULL COMMENT '渠道',
  `DATE_MON` VARCHAR(10) NOT NULL COMMENT '年月',
  `POLICY_TYPE` VARCHAR(20)  COMMENT '保单类型',
  `CLAIM_NUM` BIGINT  NOT NULL COMMENT '案件量',
  `INVOICE_NUMBER` BIGINT NOT NULL COMMENT '发票数',
  `PRICE_DJ` DECIMAL(10,2)  COMMENT '单价',
  `TOTAL` DECIMAL(10,2)  COMMENT '费用合计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  COMMENT='暖哇项目账单汇总';


drop table if exists  `CLAIM_DWD`.`DWD_TK_BILL_DETAIL` ;

CREATE TABLE `CLAIM_DWD`.`DWD_TK_BILL_DETAIL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `COMM_DATE` DATE  COMMENT '回传泰康时间',
  `POLICY_NO` VARCHAR(50)  COMMENT '甲方团单号',
  `CLAIM_TYPE` VARCHAR(20)  COMMENT '线上/线下',
   'MEDICAL_TYPE'  VARCHAR(20)  COMMENT '就诊类型门诊/住院',
  `IF_BCAJ` VARCHAR(20)  COMMENT '是否补偿案件',
  `CLAIM_DUTY` TEXT  COMMENT '赔付责任',
  `ACCEPT_NUM` VARCHAR(50)  COMMENT '受理编号',
  `YSJ_CLAIM_NO` VARCHAR(50)  COMMENT '案件号',
  `CASE_NO` VARCHAR(50)  COMMENT '保司案件号',
  `INSURED_NAME` VARCHAR(300)  COMMENT '出险人姓名',
  `INSURED_ID_NO` VARCHAR(50)  COMMENT '证件号码',
  `CLAIM_LB` VARCHAR(20)  COMMENT '案件类型',
  `C_INV_NO` BIGINT   COMMENT '账单数量',
  `COMPENSATE_AMT` DECIMAL(10,2)  COMMENT '赔付金额',
  `IS_BACK` VARCHAR(20)  COMMENT '是否回传',
  `CANCLE_TIME` VARCHAR(20)  COMMENT '撤案时间',
  `CANCLE_REASON` VARCHAR(1000) COMMENT '撤案原因',
  `CHAO8` BIGINT   COMMENT '超8张',
  `FEE` DECIMAL(10,2)  COMMENT '费用',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
)
COMMENT='泰康对账明细表'
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;

DROP TABLE IF EXISTS `DWD_UNSETTLE_CLAIM`;

CREATE TABLE `DWD_UNSETTLE_CLAIM` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
    `FAIL_DOWNLOAD` BIGINT(20) COMMENT '下载失败案件数',
    `LR_DFP` BIGINT(20) COMMENT '录入待分配案件数',
    `DLR_VOL` BIGINT(20) COMMENT '待录入案件数',
    `DYS_VOL` BIGINT(20) COMMENT '待预审案件',
    `DYYPP_VOL` BIGINT(20) COMMENT '待医院匹配条数',
    `DYYPIAJ_VOL` BIGINT(20) COMMENT '待医院匹配案件数',
    `DJBPI_VOL` BIGINT(20) COMMENT '待疾病匹配条数',
    `DJBPPAJ_VOL` BIGINT(20) COMMENT '待疾病匹配案件数',
    `DMXPI_VOL` BIGINT(20) COMMENT '待明细匹配条数',
    `DMXPIAJ_VOL` BIGINT(20) COMMENT '待明细匹配案件数',
    `DKF_VOL` BIGINT(20) COMMENT '待扣费条数',
    `DKFAJ_VOL` BIGINT(20) COMMENT '待扣费案件数',
    `DSHAJ_VOL` BIGINT(20) COMMENT '待审核案件',
    `DFHAJ_VOL` BIGINT(20) COMMENT '待复核案件',
    `GQWTAJ_VOL` BIGINT(20) COMMENT '挂起问题件案件数',
    `THLRAJ_VOL` BIGINT(20) COMMENT '退回录入案件数',
    `DPZRWS` BIGINT(20) COMMENT '待配置任务数',
    `DZLSZAJS` BIGINT(20) COMMENT '定责理算中案件数',
    `HCKZAJS` BIGINT(20) COMMENT '回传卡住案件数',
    `DHCAJS` BIGINT(20) COMMENT '待回传案件数',
    `HCSBAJS` BIGINT(20) COMMENT '回传失败案件数',
    `HCZAJS` BIGINT(20) COMMENT '回传中案件数',
    `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='未决案件统计';
CREATE TABLE `CLAIM_DWD`.`DWD_TK_BILL_TOTAL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(10) NOT NULL COMMENT '账期',
  `CLAIM_TYPE` VARCHAR(20) NOT NULL COMMENT '案件类型',
  `IS_BACK` VARCHAR(20) NOT NULL COMMENT '案件来源',
  `CLAIM_VOL` bigint  NOT NULL COMMENT '案件量',
  `C_INV_NO` bigint  NOT NULL COMMENT '发票张数',
  `PRICE_DJ` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `FEE` DECIMAL(10,2) NOT NULL COMMENT '费用小计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
)
COMMENT='泰康项目账单汇总表'
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;

drop table if exists  `CLAIM_DWD`.`DWD_TK07_TOTAL`;

CREATE TABLE `CLAIM_DWD`.`DWD_TK07_TOTAL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(10)  COMMENT '账期',
  `CLAIM_TYPE` VARCHAR(20)  COMMENT '案件类型',
   `BACK_TYPE` VARCHAR(20)  COMMENT '回传方式',
  `IS_BACK` VARCHAR(20)  COMMENT '是否结案',
  `CLAIM_VOL` bigint   COMMENT '案件量',
  `PRICE_DJ` DECIMAL(10,2)  COMMENT '单价',
  `FEE` DECIMAL(10,2)  COMMENT '费用小计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
)
COMMENT='泰康广东分公司账单汇总表'
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;



CREATE TABLE `CLAIM_DWD`.`DWD_TK10_TOTAL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(10) NOT NULL COMMENT '账期',
  `C_CVRG_DESC` VARCHAR(20) NOT NULL COMMENT '险种描述',
   `BACK_TYPE` VARCHAR(20) NOT NULL COMMENT '回传方式',
  `IS_BACK` VARCHAR(20) NOT NULL COMMENT '是否结案',
  `CLAIM_VOL` bigint  NOT NULL COMMENT '案件量',
  `PRICE_DJ` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `FEE` DECIMAL(10,2) NOT NULL COMMENT '费用小计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
)
COMMENT='泰康辽宁分公司账单汇总表'
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;






CREATE TABLE `CLAIM_DWD`.`DWD_TK11_TOTAL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(10) NOT NULL COMMENT '账期',
  `C_CVRG_DESC` VARCHAR(20) NOT NULL COMMENT '险种描述',
   `BACK_TYPE` VARCHAR(20) NOT NULL COMMENT '回传方式',
  `IS_BACK` VARCHAR(20) NOT NULL COMMENT '是否结案',
  `CLAIM_VOL` bigint  NOT NULL COMMENT '案件量',
  `PRICE_DJ` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `FEE` DECIMAL(10,2) NOT NULL COMMENT '费用小计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
)
COMMENT='泰康甘肃半流程账单汇总表'
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;



CREATE TABLE `CLAIM_DWD`.`DWD_TK09_TOTAL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(10) NOT NULL COMMENT '账期',
   `BACK_TYPE` VARCHAR(20) NOT NULL COMMENT '回传方式',
  `IS_BACK` VARCHAR(20) NOT NULL COMMENT '是否结案',
  `CLAIM_VOL` bigint  NOT NULL COMMENT '案件量',
  `PRICE_DJ` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `FEE` DECIMAL(10,2) NOT NULL COMMENT '费用小计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
)
COMMENT='泰康江苏分公司账单汇总表'
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;


CREATE TABLE `CLAIM_DWD`.`DWD_TK12_TOTAL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(10) NOT NULL COMMENT '账期',
   `BACK_TYPE` VARCHAR(20) NOT NULL COMMENT '回传方式',
  `IS_BACK` VARCHAR(20) NOT NULL COMMENT '是否结案',
  `CLAIM_VOL` bigint  NOT NULL COMMENT '案件量',
  `PRICE_DJ` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `FEE` DECIMAL(10,2) NOT NULL COMMENT '费用小计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
)
COMMENT='泰康福建分公司账单汇总表'
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;


CREATE TABLE `CLAIM_DWD`.`DWD_DJ01_TOTAL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(100) NOT NULL COMMENT '渠道',
    `DATE_MON` VARCHAR(100) NOT NULL COMMENT '结算月',
    `TREATMENT_TYPE` VARCHAR(100) NOT NULL COMMENT '发票类型',
    `CLAIM_NUM` BIGINT NOT NULL COMMENT '案件量(件)',
    `INVOICE_NUMBER` BIGINT NOT NULL COMMENT '发票数',
    `UNIT_PRICE` DECIMAL(10, 2) NOT NULL COMMENT '单价(元)',
    `TOTAL` DECIMAL(10, 2) NOT NULL COMMENT '合计(元)',
    `DATA_DT` VARCHAR(100) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='大家养老项目汇总';



CREATE TABLE `CLAIM_DWD`.`DWD_CP08_TOTAL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(100) NOT NULL COMMENT '渠道',
    `DATE_MON` VARCHAR(100)  NOT NULL COMMENT '结案时间',
    `CLAIM_NUM` VARCHAR(100)  NOT NULL COMMENT '案件数',
    `CLAIM_UNIT_PRICE` DECIMAL(10, 2) NOT NULL COMMENT '案件单价',
    `INVOICE_NUMBER` BIGINT  NOT NULL COMMENT '发票数',
    `C_INVOICE_NUMBER` BIGINT  NOT NULL COMMENT '超发票数',
    `C_UNIT_PRICE` DECIMAL(10, 2) NOT NULL COMMENT '超发票单价',
    `TOTAL` DECIMAL(10, 2) NOT NULL COMMENT '合计金额',
    `DATA_DT` VARCHAR(100) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='太保健康项目汇总';



CREATE TABLE `CLAIM_DWD`.`DWD_CP08_DETAIL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(100) NOT NULL COMMENT '渠道',
    `DATE_MON` date NOT NULL COMMENT '结案时间',
    `CLAIM_NO` VARCHAR(100) NOT NULL COMMENT '案件号',
    `INVOICE_NUMBER` BIGINT NOT NULL COMMENT '发票数',
    `C_INVOICE_NUMBER` BIGINT  NOT NULL COMMENT '超发票数',
    `UNIT_PRICE` DECIMAL(10, 2)  NOT NULL COMMENT '单价',
    `DATA_DT` VARCHAR(100) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='太保健康明细数据';



CREATE TABLE `CLAIM_DWD`.`DWD_CP02_TOTAL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(100) NOT NULL COMMENT '渠道',
    `DATE_MON` date NOT NULL COMMENT '结算月',
    `TREATMENT_TYPE` VARCHAR(100) NOT NULL COMMENT '发票类型',
    `CASELOAD` BIGINT NOT NULL COMMENT '案件量(件)',
    `C_INVOICE_NUMBER` BIGINT NOT NULL COMMENT '超发票数',
    `CJ_INVOICE_NUMBER` BIGINT NOT NULL COMMENT '超发票件数',
    `UNIT_PRICE` DECIMAL(10, 2) NOT NULL COMMENT '单价(元)',
    `TOTAL` DECIMAL(10, 2) NOT NULL COMMENT '合计(元)',
    `DATA_DT` VARCHAR(100) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='太保宁波项目汇总';






CREATE TABLE `CLAIM_DWD`.`DWD_PA02_TOTAL` (
  `DEPARTMENT_CODE` VARCHAR(50) DEFAULT 0 COMMENT '机构代码',
  `YEAR_MONTH` VARCHAR(10)  DEFAULT 0 COMMENT '年月',
    chanel_type VARCHAR(50)   COMMENT '案件类型',
  `HALF_FLOW_HC` bigint  DEFAULT 0 COMMENT '半流程案件量',
  `HALF_FLOW_PRICE` DECIMAL(10,2) DEFAULT 0 COMMENT '半流程单价',
  `HALF_FLOW_FEE_SUM` DECIMAL(10,2) DEFAULT 0 COMMENT '半流程费用合计',
  `ALL_FLOW_HC` bigint  DEFAULT 0 COMMENT '全流程案件量',
  `ALL_FLOW_PRICE` DECIMAL(10,2) DEFAULT 0 COMMENT '全流程单价',
  `ALL_FLOW_FEE_SUM` DECIMAL(10,2) DEFAULT 0 COMMENT '全流程费用合计',
  `FEE_TOTAL` DECIMAL(10,2) DEFAULT 0 COMMENT '月费用合计',
  `DATA_DT` VARCHAR(10)  COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci COMMENT='平安产险项目汇总表';

drop table if exists `CLAIM_DWD`.`DWD_GS01_TOTAL`;


CREATE TABLE `CLAIM_DWD`.`DWD_GS01_TOTAL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(100) NOT NULL COMMENT '渠道',
    `DATE_MON`  VARCHAR(10) COMMENT '结算月',
    `CLAIM_NUM` VARCHAR(100)  NOT NULL COMMENT '案件数',
    `CLAIM_TYPE` VARCHAR(50)   COMMENT '案件类型',
    `INVOICE_NUMBER` BIGINT NOT NULL COMMENT '发票数',
    `UNIT_PRICE` BIGINT NOT NULL COMMENT '单价(元)',
    `TOTAL` BIGINT NOT NULL COMMENT '合计(元)',
    `DATA_DT` VARCHAR(100) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='国寿财项目汇总';


CREATE TABLE `CLAIM_DWD`.`DWD_BH01_TOTAL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(20) NOT NULL COMMENT '渠道',
    `DATE_MON` VARCHAR(10) NOT NULL COMMENT '年月',
    `CLAIM_NUM` bigint NOT NULL COMMENT '案件数',
    `CASE_UNIT_PRICE` DECIMAL(10, 2) NOT NULL COMMENT '案件单价',
    `BILL_UNIT_PRICE` DECIMAL(10, 2) NOT NULL COMMENT '发票单价',
    `C_INVOICE_NUMBER` bigint  NOT NULL COMMENT '超发票数',
    `TOTAL` DECIMAL(10, 2) NOT NULL COMMENT '合计金额',
    `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='渤海人寿项目汇总';


CREATE TABLE `CLAIM_DWD`.`DWD_CP02_DETAIL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(100) NOT NULL COMMENT '渠道',
    `DATE_MON` date NOT NULL COMMENT '年月',
    `ACCEPT_NUM` VARCHAR(100) NOT NULL COMMENT '受理号',
    `claim_type` VARCHAR(100) NOT NULL COMMENT '案件类型（线上/线下）',
    `TREATMENT_TYPE` VARCHAR(100) NOT NULL COMMENT '就诊类型（门诊/住院）',
    `INVOICE_NUMBER` BIGINT NOT NULL COMMENT '发票数',
    `UNIT_PRICE` DECIMAL(10, 2) NOT NULL COMMENT '单价',
    `C_INVOICE_NUMBER` BIGINT NOT NULL COMMENT '超发票数',
    `DATA_DT` VARCHAR(100) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='太保宁波项目明细表';


DROP TABLE IF EXISTS `CLAIM_DWD`.`DWD_TK_CANCEL_SUMMARY_M`;

CREATE TABLE `CLAIM_DWD`.`DWD_TK_CANCEL_SUMMARY_M` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
    claim_source VARCHAR(10) COMMENT '来源',
    accept_batch_no VARCHAR(50) COMMENT '受理批次号',
    batch_case_count BIGINT COMMENT '批次案件数',
    ACCEPT_NUM VARCHAR(50) COMMENT '受理编号',
    claim_no VARCHAR(50) COMMENT '因朔桔案件号',
    group_policy_number VARCHAR(50) COMMENT '团单号',
    insured_name VARCHAR(100) COMMENT '出险人姓名',
    id_number VARCHAR(50) COMMENT '证件号码',
    liability_description TEXT COMMENT '赔付责任',
    invoice_count BIGINT COMMENT '发票数量',
    N_FINAL_COMPENSATE_AMT DECIMAL(10, 2) COMMENT '赔付金额',
    cancle_time DATE COMMENT '撤案时间',
    WITHDRAWAL_REASON VARCHAR(255) COMMENT '撤案原因',
    case_type VARCHAR(10) COMMENT '案件形式',
    C_DEPT_NAME VARCHAR(10) COMMENT '投保单位',
    `DATE_MON` VARCHAR(10) NOT NULL COMMENT '年月'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='泰康全渠道撤案月统计';

CREATE TABLE `CLAIM_DWD`.`DWD_TK_RETURN_SUMMARY_M` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道名称',
    `return_time` DATETIME COMMENT '退回时间',
    `case_number` VARCHAR(50) COMMENT '案件编号',
    `accept_number` VARCHAR(50) COMMENT '受理编号',
    `return_reason` VARCHAR(255)  COMMENT '退回原因',
    `return_person` VARCHAR(50) COMMENT '退回人',
    `date_month` VARCHAR(10) NOT NULL COMMENT '年月'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='泰康全渠道退回月统计';







drop table if exists `CLAIM_DWD`.`DWD_TK07_CLOSE_SUMMARY_M`;

CREATE TABLE `CLAIM_DWD`.`DWD_TK07_CLOSE_SUMMARY_M` (
  `insurance_claim_no` VARCHAR(50) NOT NULL COMMENT '保司赔案号',
  `C_DEPT_NAME` VARCHAR(100) DEFAULT NULL COMMENT '投保单位',
  `channel_group_policy_no` VARCHAR(50) DEFAULT NULL COMMENT '保单号',
  `claim_source` VARCHAR(10) DEFAULT NULL COMMENT '线上/线下',
  `ACCEPT_NUM` VARCHAR(50) DEFAULT NULL COMMENT '受理编号',
  `insured_name` VARCHAR(50) DEFAULT NULL COMMENT '姓名',
  `insured_id_no` VARCHAR(50) DEFAULT NULL COMMENT '证件号码',
  `C_INV_NO` BIGINT DEFAULT 0 COMMENT '账单数量',
  `postback_way` VARCHAR(20) DEFAULT NULL COMMENT '回传方式',
  `accept_batch_no` VARCHAR(50) DEFAULT NULL COMMENT '受理批次号',
    `ACCEPT_DATE` VARCHAR(50) DEFAULT NULL COMMENT '受理时间',
    `back_time` VARCHAR(50) DEFAULT NULL COMMENT '回传时间',
   `has_question_claim` VARCHAR(50) COMMENT '是否问题件',
    `DATE_MON` VARCHAR(10) NOT NULL COMMENT '年月'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='泰康广分结案月统计';


drop table if exists `CLAIM_DWD`.`DWD_TK07_CANCEL_SUMMARY_M`;

CREATE TABLE `CLAIM_DWD`.`DWD_TK07_CANCEL_SUMMARY_M` (
    channel VARCHAR(255) COMMENT '渠道',
    source VARCHAR(255) COMMENT '来源',
    accept_num VARCHAR(255) COMMENT '受理编号',
    case_number VARCHAR(255) COMMENT '案件号',
    customer_name VARCHAR(255) COMMENT '出险人姓名',
    id_number VARCHAR(255) COMMENT '证件号码',
    invoice_count INT COMMENT '发票数量',
    cancel_time DATE COMMENT '撤案时间',
    withdrawal_reason VARCHAR(255) COMMENT '撤案原因',
    case_type VARCHAR(255) COMMENT '案件形式',
    insured_unit VARCHAR(255) COMMENT '投保单位',
    `DATE_MON` VARCHAR(10) NOT NULL COMMENT '年月'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='泰康广分撤案月统计';

drop table if exists `CLAIM_DWD`.`DWD_TK_CLOSE_SUMMARY_M`;

CREATE TABLE `CLAIM_DWD`.`DWD_TK_CLOSE_SUMMARY_M` (
    `claim_source_type` VARCHAR(255) COMMENT '理赔申请来源',
    `accept_num` VARCHAR(255) COMMENT '受理编号',
    `policy_no` VARCHAR(255) COMMENT '保单号码',
    `dept_name` VARCHAR(255) COMMENT '投保单位名称',
    `insurance_claim_no` VARCHAR(255) COMMENT '保险公司案件号',
    `insured_name` VARCHAR(255) COMMENT '出险人的姓名',
    `insured_id_no` VARCHAR(255) COMMENT '出险人证件号码',
    `invoice_count` BIGINT COMMENT '关联账单的数量',
    `compensation_responsibility` TEXT COMMENT '赔付的责任描述',
    `insurance_company_channel` VARCHAR(255) COMMENT '保险公司渠道',
    `back_time` DATETIME COMMENT '数据回传的时间',
    `has_question_claim` VARCHAR(255) COMMENT '是否曾经发起过问题件处理',
    `system_acceptance_time` DATETIME COMMENT '系统受理时间',
    `acceptance_time` DATETIME COMMENT '受理时间',
    `pre_audit_earliest_outflow_time` DATETIME COMMENT '预审最早流出节点时间',
    `pre_audit_last_outflow_time` DATETIME COMMENT '预审最后流出节点时间',
    `first_internal_case_closed_time` DATETIME COMMENT '第一次内部结案时间',
    `internal_case_closed_time` DATETIME COMMENT '内部结案时间',
    `insurance_company_return_time` DATETIME COMMENT '保司退回时间',
    `auditor` VARCHAR(255) COMMENT '审核人',
    `reviewer` VARCHAR(255) COMMENT '复核人',
    `returner` VARCHAR(255) COMMENT '退回人',
    `compensation_amount` VARCHAR(50) COMMENT '赔付金额',
    `upload_time` DATETIME COMMENT '上传时间',
    `case_type` VARCHAR(255) COMMENT '案件形式',
    `date_month` VARCHAR(10) NOT NULL COMMENT '年月'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='泰康全渠道结案月统计';






CREATE TABLE CLAIM_DWD.dwd_medical_record_df (
  `C_APP_NO` varchar(50) COMMENT '申请号',
  `url` varchar(50) COMMENT '图片地址',
  `text` varchar(500) COMMENT '识别文本信息',
  `DATA_DT` VARCHAR(20) NOT NULL COMMENT '数据日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='病历信息表';

drop table if exists `CLAIM_DWD`.`DWD_POSTBACK_TOTAL`;

   CREATE TABLE CLAIM_DWD.DWD_POSTBACK_TOTAL (
    INSURE_COMPANY_CHANNEL VARCHAR(20)  COMMENT '渠道',
    DEPARTMENT_CODE VARCHAR(50)  COMMENT '机构代码',
    product_type  VARCHAR(30) COMMENT '类型',
    back_time VARCHAR(10) COMMENT '回传时间',
    claim_source VARCHAR(10) COMMENT '来源',
       ACCEPT_NUM varchar(50) COMMENT '受理编号',
    app_no   varchar(50) COMMENT '案件号',
    postback_way VARCHAR(20)  COMMENT '回传方式',
    bill_no  VARCHAR(20)  COMMENT '发票号',
    treatment_date  VARCHAR(10)  COMMENT '就诊日期',
    input_company_code	VARCHAR(20)  COMMENT '录入商代号',
    is_back VARCHAR(10) COMMENT '是否结案',
  DATA_DT VARCHAR(10)  COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  COMMENT='项目回传汇总表';





CREATE TABLE IF NOT EXISTS CLAIM_DWD.DWD_POSTBACK_INPUT_INFO (
    INSURE_COMPANY_CHANNEL VARCHAR(20) COMMENT '保险渠道',
    ACCEPT_NUM VARCHAR(50) COMMENT '受理编号',
    app_no VARCHAR(50) COMMENT '案件号',
    input_company VARCHAR(10) COMMENT '输入公司名称',
    claim_source VARCHAR(10) COMMENT '来源',
    bill_no VARCHAR(20) COMMENT '发票号',
    treatment_date DATE COMMENT '就诊日期',
    treatment_type VARCHAR(10) COMMENT '就诊类型',
    back_time DATETIME COMMENT '回传时间',
    postback_way VARCHAR(20) COMMENT '回传方式',
    is_back VARCHAR(10) COMMENT '是否结案'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='项目回传录入商信息表';


CREATE TABLE `CLAIM_DWD`.`DWD_CP07_DETAIL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(100) NOT NULL COMMENT '渠道',
    `DATE_MON` datetime NOT NULL COMMENT '年月',
    `ACCEPT_NUM` VARCHAR(100) NOT NULL COMMENT '受理号',
    `claim_type` VARCHAR(100) NOT NULL COMMENT '案件类型（线上/线下）',
    `TREATMENT_TYPE` VARCHAR(100) NOT NULL COMMENT '就诊类型（门诊/住院）',
    `INVOICE_NUMBER` BIGINT NOT NULL COMMENT '发票数',
    `UNIT_PRICE` DECIMAL(10, 2) NOT NULL COMMENT '单价',
    `C_INVOICE_NUMBER` BIGINT NOT NULL COMMENT '超发票数'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='太保财上海分公司明细表';



drop table if exists `CLAIM_DWD`.`DWD_CLAIM_RETURN_REASON`;

CREATE TABLE `CLAIM_DWD`.`DWD_CLAIM_RETURN_REASON` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
    `CLAIM_NO` VARCHAR(100) COMMENT '案件号',
      `ACCEPT_NUM` VARCHAR(50) COMMENT '受理编号',
  `GMT_CREATED` datetime COMMENT '退回时间',
  `OPER_TYPE` VARCHAR(30) COMMENT '操作类型',
  `RETURN_REASON` TEXT COMMENT '退回原因',
  `PZR` VARCHAR(200) COMMENT '配置人',
  `YSR` VARCHAR(200) COMMENT '预审人',
  `YYPPR` VARCHAR(200) COMMENT '医院匹配人',
  `ZDPPR` VARCHAR(200) COMMENT '诊断匹配人',
  `MXPPR` VARCHAR(200) COMMENT '明细匹配人',
  `KFR` VARCHAR(200) COMMENT '扣费人',
  `SHR` VARCHAR(200) COMMENT '审核人',
  `FHR` VARCHAR(200) COMMENT '复核人',
  `DEDUC_NOTE` VARCHAR(200) COMMENT '扣费备注',
    `ply_no` VARCHAR(200) COMMENT '保单号',
    `C_DEPT_NAME` VARCHAR(200) COMMENT '投保单位',
    `DATA_DT` VARCHAR(20) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='案件退回原因信息表';


CREATE TABLE `CLAIM_DWD`.`DWD_PA02_DEPARTMENT_DAY` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `DEPARTMENT_CODE` VARCHAR(20) NOT NULL COMMENT '平安产险机构',
  `IN_CLAIM_DATE` DATE NOT NULL COMMENT '进件日期',
  `IN_COUNT` BIGINT NOT NULL COMMENT '进件量',
  `TOTAL_IN_COUNT` BIGINT NOT NULL COMMENT '机构总进件量',
  `FW_INCLAIM_VOL` BIGINT NOT NULL COMMENT '4周前当日进件量',
  `OW_INCLAIM_VOL` BIGINT NOT NULL COMMENT '1周前当日进件量',
  `MONTH_HB_VOL` BIGINT NOT NULL COMMENT '4周前环比增长量',
  `WEEK_HB_VOL` BIGINT NOT NULL COMMENT '1周前环比增长量',
  `ALL_HC_THIS_DAY` BIGINT NOT NULL COMMENT '当日回传案件量',
  `HALF_FLOW_HC_VOL` BIGINT NOT NULL COMMENT '半流程回传案件量',
  `FULL_FLOW_HC_VOL` BIGINT NOT NULL COMMENT '全流程回传案件量',
  `CANCEL_VOL` BIGINT NOT NULL COMMENT '撤销量',
  `DATA_DT` VARCHAR(20) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='平安产险机构数据';



CREATE TABLE `CLAIM_DWD`.`DWD_BILL_PANEL_1` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `TOTAL_BILL_COUNT` BIGINT COMMENT '总发票数',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='总发票数';




CREATE TABLE `CLAIM_DWD`.`DWD_BILL_PANEL_2` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `MZ_BILL_COUNT` BIGINT COMMENT '门诊发票数',
  `ELEC_BILL_VOL` BIGINT COMMENT '电子发票数量',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门诊发票数';


CREATE TABLE `CLAIM_DWD`.`DWD_BILL_PANEL_3` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `ZY_BILL_COUNT` BIGINT COMMENT '住院发票数',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='住院发票数';





CREATE TABLE `CLAIM_DWD`.`DWD_BILL_PANEL_4` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `TOTAL_DETAIL_COUNT` BIGINT COMMENT '总明细条数',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='总明细条数';




CREATE TABLE `CLAIM_DWD`.`DWD_BILL_PANEL_5` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `MZ_DETAIL_COUNT` BIGINT COMMENT '门诊明细条数',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='门诊明细条数';



CREATE TABLE `CLAIM_DWD`.`DWD_BILL_PANEL_6` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `ZY_BILL_DETAIL_COUNT` BIGINT COMMENT '住院发票明细数',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='住院发票明细数';


CREATE TABLE `CLAIM_DWD`.`DWD_BILL_PANEL_7` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `ELEC_BILL_CLAIM_VOL` BIGINT COMMENT '电子发票案件数',
  `ALL_ELEC_BILL_CLAIM_VOL` BIGINT COMMENT '全案电子发票案件数',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='电子发票案件数';






CREATE TABLE `CLAIM_DWD`.`DWD_BISIC_DATA_PANEL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `CREATE_TIME` DATE COMMENT '时间',
  `TOTAL_CLAIM_COUNT` BIGINT COMMENT '受理案件量',
  `TOTAL_MZ_CLAIM_COUNT` BIGINT COMMENT '门诊案件量',
  `HOSPITAL_CLAIM_COUNT` BIGINT COMMENT '住院案件数',
  `MZ_ONLINE_CLAIM_COUNT` BIGINT COMMENT '门诊线上案件数',
  `MZ_OFFLINE_CLAIM_COUNT` BIGINT COMMENT '门诊线下案件数',
  `ALL_FLOW_CLAIM_COUNT` BIGINT COMMENT '全流程案件量',
  `HALF_FLOW_CLAIM_COUNT` BIGINT COMMENT '半流程案件量',
  `TOTAL_HALF_ALL_FLOW` BIGINT COMMENT '全流程和半流程案件量之和',
  `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='基础数据看板';


drop table if exists `CLAIM_DWD`.`DWD_COMPANY_CHANNEL_HOUR`;

CREATE TABLE `CLAIM_DWD`.`DWD_COMPANY_CHANNEL_HOUR` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `JJL` BIGINT COMMENT '进件量',
  `T_CRT_TIME` DATE COMMENT '进件日期',
  `JJ_HOUR` BIGINT COMMENT '进件小时',
  `JJ_DAY_HOUR` VARCHAR(30) COMMENT '进件天小时',
  `DATA_DT` VARCHAR(30) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='进件量日分布统计';



drop table if exists `CLAIM_DWD`.`tmp_0919`;


CREATE TABLE `CLAIM_DWD`.`tmp_0919` (
    main_order_number VARCHAR(255), -- 主团单号
    claim_number VARCHAR(255), -- 赔案号
    insured_age INT, -- 投保年龄
    settlement_date DATE, -- 结案日期
    accident_time DATETIME, -- 出险时间
    treatment_date DATE, -- 就诊日期
    insured_name VARCHAR(255), -- 出险人姓名
    insured_gender VARCHAR(255), -- 出险人性别
    disease_code VARCHAR(255), -- 疾病代码
    disease_name VARCHAR(255), -- 疾病名称
    hospital_city VARCHAR(255), -- 就诊医院所在城市
    hospital_name VARCHAR(255), -- 就诊医院名称
    hospital_province VARCHAR(255), -- 就诊医院所在省市
    liability_name VARCHAR(255), -- 责任名称
    claim_conclusion VARCHAR(255), -- 理赔结论
    insured_id_number VARCHAR(255), -- 出险人证件号
    payout_amount DECIMAL(10,2) -- 赔付金额
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;



CREATE TABLE `CLAIM_DWD`.`tmp_0919` (
    主团单号 VARCHAR(255),
    赔案号 VARCHAR(255),
    投保年龄 VARCHAR(255),
    结案日期 VARCHAR(255),
    出险时间 VARCHAR(255),
    就诊日期 VARCHAR(255),
    出险人姓名 VARCHAR(255),
    出险人性别 VARCHAR(255),
    疾病代码 VARCHAR(255),
    疾病名称 VARCHAR(255),
    就诊医院所在城市 VARCHAR(255),
    就诊医院名称 VARCHAR(255),
    就诊医院所在省市 VARCHAR(255),
    责任名称 VARCHAR(255),
    理赔结论 VARCHAR(255),
    出险人证件号 VARCHAR(255),
    赔付金额 DECIMAL(10,2)
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ;







drop table if exists `CLAIM_DWD`.`DWD_CP01_TREATMENT_INFO`;


CREATE TABLE `CLAIM_DWD`.`DWD_CP01_TREATMENT_INFO` (
    file_num VARCHAR(255) COMMENT '中智案卷号', -- 中智案卷号
    claim_no VARCHAR(255) COMMENT '申请号', -- 申请号
    acceptance_no VARCHAR(255) COMMENT '受理编号', -- 受理编号
    cust_company_code VARCHAR(255) COMMENT '公司编号', -- 公司编号
    cust_group_code VARCHAR(255) COMMENT '集团编号', -- 集团编号
    channel_customer_no VARCHAR(255) COMMENT '雇员编号', -- 雇员编号
    insured_name VARCHAR(255) COMMENT '雇员姓名', -- 雇员姓名
    insured_gender VARCHAR(255) COMMENT '雇员性别', -- 雇员性别
    channel_customer_no_2 VARCHAR(255) COMMENT '出险人雇员编号', -- 出险人雇员编号
    insured_name_2 VARCHAR(255) COMMENT '出险人姓名', -- 出险人姓名
    insured_id_no VARCHAR(255) COMMENT '证件号码', -- 证件号码
    insured_gender_2 VARCHAR(255) COMMENT '出险人性别', -- 出险人性别
    insured_birthday DATE COMMENT '出险人出生日期', -- 出险人出生日期
    insured_relation VARCHAR(255) COMMENT '出险人与雇员关系', -- 出险人与雇员关系
    apply_tm DATETIME COMMENT '申请时间', -- 申请时间
    t_accident_tm DATETIME COMMENT '出险时间', -- 出险时间
    bill_num INT COMMENT '账单张数', -- 账单张数
    claim_amount VARCHAR(255) COMMENT '索赔金额', -- 索赔金额
    final_compensate_amt VARCHAR(255) COMMENT '中智赔付金额', -- 中智赔付金额
    compensate_conclusion VARCHAR(255) COMMENT '赔付结论', -- 赔付结论
    compensate_conclusion_description TEXT COMMENT '赔付结论描述', -- 赔付结论描述
    acceptance_date VARCHAR(255) COMMENT '受理日期', -- 受理日期
    insure_effective_date VARCHAR(255) COMMENT '保单生效日期', -- 保单生效日期
    insure_expiry_date VARCHAR(255) COMMENT '保单截止日期', -- 保单截止日期
    claim_source VARCHAR(255) COMMENT '申请来源', -- 申请来源
    ply_no VARCHAR(255) COMMENT '分单号', -- 分单号
    end_date VARCHAR(255) COMMENT '结案日期', -- 结案日期
    invoice_no VARCHAR(255) COMMENT '发票号', -- 发票号
    serial_no VARCHAR(255) COMMENT '明细序号', -- 明细序号
    pay_name VARCHAR(255) COMMENT '诊疗名称', -- 诊疗名称
    extra_category_name VARCHAR(255) COMMENT '明细大项', -- 明细大项
    num VARCHAR(255) COMMENT '数量', -- 数量
    secu_typ VARCHAR(255) COMMENT '医保类型', -- 医保类型
    sum_amt VARCHAR(255) COMMENT '总金额', -- 总金额
    categ_selfpay_amt VARCHAR(255) COMMENT '分类自负', -- 分类自负
    self_expense VARCHAR(255) COMMENT '自费', -- 自费
    medicare_payment_amt VARCHAR(255) COMMENT '医保', -- 医保
    third_pay_amt VARCHAR(255) COMMENT '第三方', -- 第三方
    reasonable_amt VARCHAR(255) COMMENT '可理算', -- 可理算
    deduct_amt VARCHAR(255) COMMENT '扣减', -- 扣减
    compensate_amt VARCHAR(255) COMMENT '最终赔付', -- 最终赔付
    deductle_amt VARCHAR(255) COMMENT '免赔额', -- 免赔额
    compensate_result VARCHAR(255) COMMENT '赔付结果', -- 赔付结果
    conclusion_description VARCHAR(500) COMMENT '结论描述', -- 结论描述
    year VARCHAR(10) COMMENT '年份', -- 年份
    data_month VARCHAR(10) COMMENT '年月' -- 年份
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  COMMENT='中智理赔明细层';




drop table if exists `CLAIM_DWD`.`DWD_CP01_INVOICE_INFO`;

CREATE TABLE CLAIM_DWD.DWD_CP01_INVOICE_INFO (
    file_num VARCHAR(255) COMMENT '中智案卷号',
    claim_no VARCHAR(255) COMMENT '申请号',
    acceptance_no VARCHAR(255) COMMENT '受理编号',
    cust_company_code VARCHAR(255) COMMENT '公司编号',
    cust_group_code VARCHAR(255) COMMENT '集团编号',
    channel_customer_no VARCHAR(255) COMMENT '雇员编号',
    insured_name VARCHAR(255) COMMENT '雇员姓名',
    insured_gender VARCHAR(255) COMMENT '雇员性别',
    insured_channel_customer_no VARCHAR(255) COMMENT '出险人雇员编号',
    insured_channel_name VARCHAR(255) COMMENT '出险人姓名',
    insured_channel_gender VARCHAR(255) COMMENT '出险人性别',
    insured_birthday DATE COMMENT '出险人出生日期',
    insured_relation VARCHAR(255) COMMENT '出险人与雇员关系',
    apply_tm DATETIME COMMENT '申请时间',
    accident_tm DATETIME COMMENT '出险时间',
    bill_num VARCHAR(255) COMMENT '账单张数',
    claim_amount VARCHAR(255) COMMENT '索赔金额',
    compensate_amount VARCHAR(255) COMMENT '中智赔付金额',
    compensate_conclusion VARCHAR(255) COMMENT '赔付结论',
    accept_date DATE COMMENT '受理日期',
    insure_effective_date DATETIME COMMENT '保单生效日期',
    insure_expiry_date DATETIME COMMENT '保单截止日期',
    claim_source VARCHAR(255) COMMENT '申请来源',
    ply_no VARCHAR(255) COMMENT '保单号',
    inv_no VARCHAR(255) COMMENT '发票号',
    visit_bgn_tm DATETIME COMMENT '就诊开始时间',
    visit_end_tm DATETIME COMMENT '就诊结束时间',
    response_desc VARCHAR(255) COMMENT '责任',
    sum_amt VARCHAR(255) COMMENT '总金额',
    social_give_amount VARCHAR(255) COMMENT '医保支付金额',
    categ_selfpay VARCHAR(255) COMMENT '分类自负金额',
    self_expense VARCHAR(255) COMMENT '自费金额',
    third_pay_amt VARCHAR(255) COMMENT '第三方支付金额',
    extra_pay_amount VARCHAR(255) COMMENT '附加支付',
    final_pay VARCHAR(255) COMMENT '最终赔付金额',
    pay_result VARCHAR(255) COMMENT '赔付结果',
    deduct_amt VARCHAR(255) COMMENT '扣减金额',
    deductle_amt VARCHAR(255) COMMENT '免赔额',
    hospital_name VARCHAR(255) COMMENT '医院名称',
    hospital_location VARCHAR(255) COMMENT '医院所属地',
    diag_cde VARCHAR(255) COMMENT '疾病码',
    diag_name VARCHAR(255) COMMENT '疾病名称',
    insured_id_no VARCHAR(255) COMMENT '证件号码',
    end_date DATE COMMENT '结案日期',
    year VARCHAR(10) COMMENT '年份', -- 年份
    data_month VARCHAR(10) COMMENT '年月' -- 年份
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  COMMENT='中智理赔发票层';

drop table if exists `CLAIM_DWD`.`DWD_CP01_CLAIM_INFO`;

CREATE TABLE CLAIM_DWD.DWD_CP01_CLAIM_INFO (
    file_num VARCHAR(255) COMMENT '中智案卷号',
    claim_no VARCHAR(255) COMMENT '申请号',
    acceptance_no VARCHAR(255) COMMENT '受理编号',
    cust_company_code VARCHAR(255) COMMENT '公司编号',
    cust_group_code VARCHAR(255) COMMENT '集团编号',
    channel_customer_no VARCHAR(255) COMMENT '雇员编号',
    insured_name VARCHAR(255) COMMENT '雇员姓名',
    insured_gender VARCHAR(255) COMMENT '雇员性别',
    insured_channel_customer_no VARCHAR(255) COMMENT '出险人雇员编号',
    insured_channel_name VARCHAR(255) COMMENT '出险人姓名',
    insured_channel_gender VARCHAR(255) COMMENT '出险人性别',
    insured_birthday DATE COMMENT '出险人出生日期',
    insured_relation VARCHAR(255) COMMENT '出险人与雇员关系',
    apply_tm DATETIME COMMENT '申请时间',
    accident_tm DATETIME COMMENT '出险时间',
    bill_num VARCHAR(50) COMMENT '账单张数',
    claim_amount VARCHAR(50) COMMENT '索赔金额',
    compensate_amount VARCHAR(50) COMMENT '中智赔付金额',
    compensate_conclusion VARCHAR(255) COMMENT '赔付结论',
    compensate_description TEXT COMMENT '赔付结论描述',
    accept_date DATE COMMENT '受理日期',
    insure_effective_date DATETIME COMMENT '保单生效日期',
    insure_expiry_date DATETIME COMMENT '保单截止日期',
    claim_source VARCHAR(255) COMMENT '申请来源',
    insured_id_no VARCHAR(255) COMMENT '证件号码',
    end_date DATE COMMENT '结案日期',
    year VARCHAR(10)  COMMENT '年份',
    data_month VARCHAR(10)  COMMENT '月份标识'
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  COMMENT='中智理赔案件层';






CREATE TABLE CLAIM_DWD.`DWD_VERIFY_REASON_ANALY` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
    `GMT_CREATED` DATE COMMENT '进件日期',
    `RULE_CODE` VARCHAR(20) COMMENT '规则代码',
    `RULE_DESC` VARCHAR(255) COMMENT '规则描述',
    `COUNT_BUSI` BIGINT(20) COMMENT '规则量',
    `DATA_DT` VARCHAR(20) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  COMMENT='人工审核原因分析表';

CREATE TABLE CLAIM_DWD.DWD_CHARG_REASON_ANALY (
    INSURE_COMPANY_CHANNEL VARCHAR(50) COMMENT '渠道',
    COMM_DATE DATE COMMENT '时间',
    LAYER VARCHAR(30) COMMENT '层级',
    REASON_NOTES TEXT COMMENT '原因', -- 使用TEXT类型来存储较长的字符串
    CLAIM_VOL BIGINT(20) COMMENT '案件数',
    CLAIM_NO VARCHAR(50) COMMENT '样例案件',
    DATA_DT VARCHAR(20) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='人工扣费原因分析表';





CREATE TABLE CLAIM_DWD.DWD_IMAGE_ASSIGN_ENTER (
    INSURE_COMPANY_CHANNEL VARCHAR(50) COMMENT '渠道',
    ENTER_MERCHANT VARCHAR(30) COMMENT '录入商',
    COMM_DATE DATE COMMENT '进件日期',
    DIVISION_NU BIGINT(20) COMMENT '分配数量',
    LRL BIGINT(20) COMMENT '录入回传数量',
    DATA_DT VARCHAR(20) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='录入商日报';


CREATE TABLE CLAIM_DWD.DWD_LRL_DAY_COUNT (
    `ENTER_MERCHANT` VARCHAR(50) COMMENT '录入商',
    `T_CRT_TIME` DATE COMMENT '进件日期',
    `JJ_HOUR` VARCHAR(20) COMMENT '进件小时',
    `DIVISION_NU` BIGINT(20) COMMENT '分配数量',
    `LRL` BIGINT(20) COMMENT '录入回传数量',
    `DATA_DT` VARCHAR(20) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='录入量日分布统计';






drop table if exists CLAIM_DWD.DWD_TK07_BATCH_INFO;

CREATE TABLE CLAIM_DWD.DWD_TK07_BATCH_INFO  (
  `accept_batch_no` VARCHAR(255) COMMENT '收单批次号',
  `accept_num` VARCHAR(255) COMMENT '报案号',
  `insurance_batch_no` VARCHAR(255) COMMENT '保司批次号',
  `policy_no` VARCHAR(255) COMMENT '保单号',
  `insurance_claim_no` VARCHAR(255) COMMENT '保司赔案号',
  `customer_no` VARCHAR(255) COMMENT '客户号',
  `claimant_name` VARCHAR(255) COMMENT '出险人姓名',
  `certificate_number` VARCHAR(255) COMMENT '证件号码',
  `visit_type` VARCHAR(255) COMMENT '就诊类型',
  `responsibility` VARCHAR(255) COMMENT '责任',
  `invoice_number` VARCHAR(255) COMMENT '发票号码',
  `visit_start_date` DATETIME COMMENT '就诊起始日',
  `visit_end_date` DATETIME COMMENT '就诊终止日',
  `invoice_total_amount` DECIMAL(10,2) COMMENT '发票总金额',
  `social_insurance_range` DECIMAL(10,2) COMMENT '社保范围内',
  `partial_item_self_pay` DECIMAL(10,2) COMMENT '部分项目自付',
  `self_pay` DECIMAL(10,2) COMMENT '自费',
  `personal_self_pay_total` DECIMAL(10,2) COMMENT '个人自付总额',
  `social_amount` DECIMAL(10,2) COMMENT '社保统筹金额',
  `personal_cash_payment` VARCHAR(255) COMMENT '个人现金支付',
  `deduc_amount` DECIMAL(10,2) COMMENT '发票使用免赔额',
  `invoice_amount` DECIMAL(10,2) COMMENT '发票赔付金额',
  `invoice_conclusion` VARCHAR(255) COMMENT '发票层赔付结论',
  `internal_conclusion` VARCHAR(255) COMMENT '内部结论',
  `case_status` VARCHAR(255) COMMENT '案件状态',
    `T_UPD_TM` VARCHAR(255) COMMENT '结案时间',
  `withdrawal_reason` VARCHAR(255) COMMENT '撤案原因',
  `question_reason` VARCHAR(255) COMMENT '问题件生成原因',
  `insurance_accept_batch_no` VARCHAR(255) COMMENT '保司收单批次号',
  `phone_number` VARCHAR(255) COMMENT '电话号码',
  `collected_phone_no` VARCHAR(255) COMMENT '录入商采集电话号码',
  `pre_phone_no` VARCHAR(255) COMMENT '保全电话号码',
  `rec_person_phone_no` VARCHAR(255) COMMENT '领款人手机号码'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='泰康广分批次数据';


drop table if exists CLAIM_DWD.DWD_TK04_BANK_INFO;

CREATE TABLE CLAIM_DWD.DWD_TK04_BANK_RETURN_INFO (
  `accept_batch_no` VARCHAR(255) COMMENT '受理批次号',
  `acceptance_no` VARCHAR(255) COMMENT '受理编号',
  `case_status` VARCHAR(255) COMMENT '案件状态',
  `enterprise` VARCHAR(255) COMMENT '登记部门',
  `source` VARCHAR(255) COMMENT '来源',
  `C_APP_NME` VARCHAR(255) COMMENT '姓名',
  `C_APP_CERT_CDE` VARCHAR(255) COMMENT '证件号码',
  `invoice_number` VARCHAR(255) COMMENT '发票号',
  `invoice_amount` DECIMAL(10,2) COMMENT '发票金额',
  `refund_amount` DECIMAL(10,2) COMMENT '退票金额',
  `rejection_reason` VARCHAR(255) COMMENT '拒赔原因',
  `invoice_count` INT COMMENT '发票张数',
  `remark` VARCHAR(255) COMMENT '备注'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='农商行退票清单';






CREATE TABLE CLAIM_DWD.DWD_TK_ALL_BATCH_INFO (
    accept_batch_no VARCHAR(50) COMMENT '受理批次号',
    ACCEPT_NUM VARCHAR(50) COMMENT '报案号',
    insurance_batch_no VARCHAR(50) COMMENT '保司批次号',
    insure_accept_batch_no VARCHAR(50) COMMENT '保司收单批次号',
    policy_no VARCHAR(50) COMMENT '保单号',
    insurance_claim_no VARCHAR(50) COMMENT '保司赔案号',
    channel_customer_no VARCHAR(50) COMMENT '客户号',
    customer_name VARCHAR(50) COMMENT '出险人姓名',
    id_no VARCHAR(50) COMMENT '证件号码',
    visit_type VARCHAR(50) COMMENT '就诊类型',
    case_status VARCHAR(50) COMMENT '案件状态',
    apply_layer_conclusion VARCHAR(50) COMMENT '申请层赔付结论',
    invoice_number VARCHAR(50) COMMENT '发票号',
    diagnosis VARCHAR(50) COMMENT '诊断',
    disease_code VARCHAR(50) COMMENT '疾病代码',
    invoice_start_time DATETIME COMMENT '发票起始日',
    invoice_end_time DATETIME COMMENT '发票终止日',
    hospital_name VARCHAR(50) COMMENT '医院名称',
    respon_des VARCHAR(50) COMMENT '责任描述',
    total_amount DECIMAL(10,2) COMMENT '总金额',
    category_self_pay DECIMAL(10,2) COMMENT '分类自付',
    self_expense DECIMAL(10,2) COMMENT '自费',
    medical_insurance_payment DECIMAL(10,2) COMMENT '医保支付金额',
    deduction_amount DECIMAL(10,2) COMMENT '扣减金额',
    third_party_payment DECIMAL(10,2) COMMENT '第三方支付金额',
    reasonable_amount DECIMAL(10,2) COMMENT '可理算金额',
    final_payment DECIMAL(10,2) COMMENT '赔付金额',
    invoice_con VARCHAR(50) COMMENT '发票层赔付结论',
    invoice_con_des VARCHAR(50) COMMENT '发票层结论描述'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  COMMENT='泰康全渠道批次数据';



drop table if exists CLAIM_DWD.DWD_LR_ORIGINAL_INFO;

CREATE TABLE IF NOT EXISTS CLAIM_DWD.DWD_LR_ORIGINAL_INFO  (
    third_party_code VARCHAR(50) COMMENT '第三方编码',
    create_time VARCHAR(25) COMMENT '创建时间',
    update_time VARCHAR(25) COMMENT '修改时间',
    acceptNum VARCHAR(25) COMMENT '受理编号',
    bill_no VARCHAR(25) COMMENT '账单号',
    billName VARCHAR(25) COMMENT '账单姓名',
    visitTime VARCHAR(25) COMMENT '就诊日期',
    sepcialNeed VARCHAR(5) COMMENT '是否特需',
    outpatientSpecial VARCHAR(5) COMMENT '是否门特',
    billType VARCHAR(5) COMMENT '账单类型'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4  COMMENT='录入商原始信息';



CREATE TABLE `CLAIM_DWD`.`DWD_RB01_TOTAL` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(20) NOT NULL COMMENT '渠道',
    `DATE_MON` VARCHAR(10) NOT NULL COMMENT '年月',
    `CLAIM_TYPE` VARCHAR(20) NOT NULL COMMENT '案件类型',
    `CLAIM_NUM` bigint NOT NULL COMMENT '案件数',
    `CASE_UNIT_PRICE` DECIMAL(10, 2) NOT NULL COMMENT '案件单价',
    `TOTAL` DECIMAL(10, 2) NOT NULL COMMENT '合计金额',
    `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='中国人民财产保险项目汇总';









DROP TABLE IF EXISTS `CLAIM_DWD`.`DWD_WORK_HOUR_PANEL`;

CREATE TABLE `CLAIM_DWD`.`DWD_WORK_HOUR_PANEL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
  `COMM_DATE` DATE COMMENT '时间',
  `PRE_EXAMINE_SJGS` DECIMAL(10,2) COMMENT '预审实际工时',
  `HOSPITAL_SJGS` DECIMAL(10,2) COMMENT '医院匹配实际工时',
  `DIAGNOSE_SJGS` DECIMAL(10,2) COMMENT '诊断匹配实际工时',
  `DETAIL_SJGS` DECIMAL(10,2) COMMENT '明细匹配实际工时',
  `CHARGE_SJGS` DECIMAL(10,2) COMMENT '扣费实际工时',
  `CONFIG_SJGS` DECIMAL(10,2) COMMENT '配置实际工时',
  `EXAMINE_SJGS` DECIMAL(10,2) COMMENT '审核实际工时',
  `COMPLEX_SJGS` DECIMAL(10,2) COMMENT '复核实际工时',
  `PRE_EXAMINE_WQGS` DECIMAL(10,2) COMMENT '预审完全工时',
  `HOSPITAL_WQGS` DECIMAL(10,2) COMMENT '医院匹配完全工时',
  `DIAGNOSE_WQGS` DECIMAL(10,2) COMMENT '诊断匹配完全工时',
  `DETAIL_WQGS` DECIMAL(10,2) COMMENT '明细匹配完全工时',
  `CHARGE_WQGS` DECIMAL(10,2) COMMENT '扣费完全工时',
  `CONFIG_WQGS` DECIMAL(10,2) COMMENT '配置完全工时',
  `EXAMINE_WQGS` DECIMAL(10,2) COMMENT '审核完全工时',
  `COMPLEX_WQGS` DECIMAL(10,2) COMMENT '复核完全工时',
  `PRE_EXAMINE_GS` DECIMAL(10,2) COMMENT '预审在岗工时',
  `HOSPITAL_GS` DECIMAL(10,2) COMMENT '医院在岗工时',
  `DIAGNOSE_GS` DECIMAL(10,2) COMMENT '诊断在岗工时',
  `DETAIL_GS` DECIMAL(10,2) COMMENT '明细在岗工时',
  `CHARGE_GS` DECIMAL(10,2) COMMENT '扣费在岗工时',
  `CONFIG_GS` DECIMAL(10,2) COMMENT '配置在岗工时',
  `EXAMINE_GS` DECIMAL(10,2) COMMENT '审核在岗工时',
  `COMPLEX_GS` DECIMAL(10,2) COMMENT '复核在岗工时',
  `MANAGE_GS` DECIMAL(10,2) COMMENT '管理在岗工时',
  `ZDGZ_SJGS` DECIMAL(10,2) COMMENT '诊断规则实际工时',
  `ZDGZ_WQGS` DECIMAL(10,2) COMMENT '诊断规则完全工时',
    `DATA_DT` VARCHAR(10) COMMENT '调度时间'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='人工工时看板';





DROP TABLE IF EXISTS `CLAIM_DWD`.`DWD_UNSETTLE_CLAIM`;

CREATE TABLE `CLAIM_DWD`.`DWD_UNSETTLE_CLAIM` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '渠道',
    `FAIL_DOWNLOAD` BIGINT(20) COMMENT '下载失败案件数',
    `LR_DFP` BIGINT(20) COMMENT '录入待分配案件数',
    `DLR_VOL` BIGINT(20) COMMENT '待录入案件数',
    `DYS_VOL` BIGINT(20) COMMENT '待预审案件',
    `DYYPP_VOL` BIGINT(20) COMMENT '待医院匹配条数',
    `DYYPIAJ_VOL` BIGINT(20) COMMENT '待医院匹配案件数',
    `DJBPI_VOL` BIGINT(20) COMMENT '待疾病匹配条数',
    `DJBPPAJ_VOL` BIGINT(20) COMMENT '待疾病匹配案件数',
    `DMXPI_VOL` BIGINT(20) COMMENT '待明细匹配条数',
    `DMXPIAJ_VOL` BIGINT(20) COMMENT '待明细匹配案件数',
    `DKF_VOL` BIGINT(20) COMMENT '待扣费条数',
    `DKFAJ_VOL` BIGINT(20) COMMENT '待扣费案件数',
    `DSHAJ_VOL` BIGINT(20) COMMENT '待审核案件',
    `DFHAJ_VOL` BIGINT(20) COMMENT '待复核案件',
    `GQWTAJ_VOL` BIGINT(20) COMMENT '挂起问题件案件数',
    `THLRAJ_VOL` BIGINT(20) COMMENT '退回录入案件数',
    `DPZRWS` BIGINT(20) COMMENT '待配置任务数',
    `DZLSZAJS` BIGINT(20) COMMENT '定责理算中案件数',
    `HCKZAJS` BIGINT(20) COMMENT '回传卡住案件数',
    `DHCAJS` BIGINT(20) COMMENT '待回传案件数',
    `HCSBAJS` BIGINT(20) COMMENT '回传失败案件数',
    `HCZAJS` BIGINT(20) COMMENT '回传中案件数',
    `DATA_DT` VARCHAR(10) COMMENT '调度日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='未决案件统计';






drop table if exists `CLAIM_DWD`.`DWD_YSJ_LR_ERROR_INFO`;


CREATE TABLE `CLAIM_DWD`.`DWD_YSJ_LR_ERROR_INFO` (
    claim_no VARCHAR(50) COMMENT '受理编号',
    back_time VARCHAR(50) COMMENT '回传时间',
    bill_no VARCHAR(50) COMMENT '发票号',
    lr_name VARCHAR(50) COMMENT '录入姓名',
    fh_name VARCHAR(50) COMMENT '复核姓名',
    bill_user_name_actual VARCHAR(50) COMMENT '发票姓名实际值',  -- 发票姓名实际
    bill_payer_entered VARCHAR(50) COMMENT '发票姓名录入值',     -- 发票姓名录入
    treatment_date_actual VARCHAR(50) COMMENT '就诊日期实际值',  -- 就诊日期实际
    treatment_date_entered VARCHAR(50) COMMENT '就诊日期录入值', -- 就诊日期录入
    hospital_name_actual VARCHAR(50) COMMENT '医院名称实际值',  -- 医院名称实际
    hospital_name_entered VARCHAR(50) COMMENT '医院名称录入值', -- 医院名称录入
    bill_amount_actual DECIMAL(10,2) COMMENT '发票金额实际值',    -- 发票金额实际
    total_amount_entered DECIMAL(10,2) COMMENT '发票金额录入值',  -- 发票金额录入
    in_hospital_date_actual VARCHAR(50) COMMENT '入院日期实际值',-- 入院日期实际
    in_hospital_date_entered VARCHAR(50) COMMENT '入院日期录入值',-- 入院日期录入
    out_hospital_date_actual VARCHAR(50) COMMENT '出院日期实际值',-- 出院日期实际
    out_hospital_date_entered VARCHAR(50) COMMENT '出院日期录入值',-- 出院日期录入
    bill_type_actual VARCHAR(50) COMMENT '账单类型实际值',       -- 账单类型实际
    bill_type_entered VARCHAR(50) COMMENT '账单类型录入值',      -- 账单类型录入
    bill_shape_actual VARCHAR(50) COMMENT '账单形式实际值',      -- 账单形式实际
    bill_form_entered VARCHAR(50) COMMENT '账单形式录入值',      -- 账单形式录入
    vip_type_actual VARCHAR(50) COMMENT '是否特需实际值',        -- 是否特需实际
    special_entered VARCHAR(50) COMMENT '是否特需录入值',        -- 是否特需录入
    mergency_type_actual VARCHAR(50) COMMENT '是否急诊实际值',   -- 是否急诊实际
    emergency_treatment_entered VARCHAR(50) COMMENT '是否急诊录入值', -- 是否急诊录入
    health_type_actual VARCHAR(50) COMMENT '是否康复实际值',     -- 是否康复实际
    recovery_entered VARCHAR(50) COMMENT '是否康复录入值',       -- 是否康复录入
    social_pay_amount_actual DECIMAL(10,2) COMMENT '社保支付金额实际值', -- 社保支付金额实际
    social_security_payment_entered DECIMAL(10,2) COMMENT '社保支付金额录入值', -- 社保支付金额录入
    personal_pay_amount_actual DECIMAL(10,2) COMMENT '个人账户支付实际值', -- 个人账户支付实际
    personal_account_payment_entered DECIMAL(10,2) COMMENT '个人账户支付录入值', -- 个人账户支付录入
    deductible_actual DECIMAL(10,2) COMMENT '起付线实际值',    -- 起付线实际
    start_pay_line_entered DECIMAL(10,2) COMMENT '起付线录入值',-- 起付线录入
    class_pay_amount_actual DECIMAL(10,2) COMMENT '分类自负金额实际值', -- 分类自负金额实际
    classified_self_payment_entered DECIMAL(10,2) COMMENT '分类自负金额录入值', -- 分类自负金额录入
    own_pay_amount_actual DECIMAL(10,2) COMMENT '自费金额实际值', -- 自费金额实际
    own_payment_entered DECIMAL(10,2) COMMENT '自费金额录入值',   -- 自费金额录入
    extra_pay_amount_actual DECIMAL(10,2) COMMENT '附加支付金额实际值', -- 附加支付金额实际
    additional_payment_entered DECIMAL(10,2) COMMENT '附加支付金额录入值', -- 附加支付金额录入
    third_party_pay_amount_actual DECIMAL(10,2) COMMENT '第三方支付金额实际值', -- 第三方支付金额实际
    third_pay_amount_entered DECIMAL(10,2) COMMENT '第三方支付金额录入值', -- 第三方支付金额录入
    remark_actual VARCHAR(50) COMMENT '账单备注实际值',         -- 账单备注实际
    remark_entered VARCHAR(50) COMMENT '账单备注录入值',        -- 账单备注录入
    hospital_dept_actual VARCHAR(50) COMMENT '科室实际值',  -- 科室实际
    department_code_entered VARCHAR(50) COMMENT '科室录入值',-- 科室录入
    diagnosis1_actual VARCHAR(50) COMMENT '诊断1实际值',     -- 诊断1实际
    diagnosis1_entered VARCHAR(50) COMMENT '诊断1录入值',    -- 诊断1录入
    diagnosis2_actual VARCHAR(50) COMMENT '诊断2实际值',     -- 诊断2实际
    diagnosis2_entered VARCHAR(50) COMMENT '诊断2录入值',    -- 诊断2录入
    diagnosis3_actual VARCHAR(50) COMMENT '诊断3实际值',
    diagnosis3_entered VARCHAR(50) COMMENT '诊断3录入值',
    data_dt VARCHAR(10) COMMENT '数据日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='因朔桔录入差错表';



CREATE TABLE CLAIM_DWD.DWD_POSTBACK_RESULT (
    insure_company_channel VARCHAR(50) COMMENT '大渠道',
    accept_num VARCHAR(50) COMMENT '受理编号',
    app_no VARCHAR(50) COMMENT '申请号',
    insurance_claim_no VARCHAR(50) COMMENT '保司赔案号',
    postback_way VARCHAR(50) COMMENT '回传方式：H-半流程，W-全流程',
    back_time VARCHAR(50) COMMENT '回传时间',
    back_status VARCHAR(50) COMMENT '回传状态',
    C_HANDLE_STAFF VARCHAR(50) COMMENT '审核人员',
    C_REVIEWER_STAFF VARCHAR(50) COMMENT '复核人员',
    data_dt VARCHAR(10) COMMENT '数据日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='回传结果表';




CREATE TABLE CLAIM_DWD.DWD_CANCEL_RESULT (
    INSURE_COMPANY_CHANNEL VARCHAR(255) COMMENT '大渠道',
    ACCEPT_NUM VARCHAR(255) COMMENT '受理编号',
    CLAIM_NO VARCHAR(255) COMMENT '案件号',
    cancle_time DATE COMMENT '撤案时间',
    WITHDRAWAL_REASON VARCHAR(255) COMMENT '撤案原因'
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='撤案结果表';





CREATE TABLE CLAIM_DWD.`DWD_CLAIM_COUNT_DAY_HOUR` (
    `INSURE_COMPANY_CHANNEL` VARCHAR(50) COMMENT '保险公司渠道',
    `GMT_CREATED` DATE COMMENT '创建时间',
    `HOUR_NUM` INT COMMENT '小时',
    `JJL` BIGINT COMMENT '进件量',
    `LRL` BIGINT  COMMENT '录入量',
    `DRHCAL` BIGINT COMMENT '当日回传案件量',
    `QUESTION_CLAIM_VOL` BIGINT COMMENT '问题件案件数',
    `DATA_DT` VARCHAR(20) COMMENT '数据日期'
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='日案件量小时报表';


drop table if exists CLAIM_DWD.DWD_API_MONITOR_RESULT;

CREATE TABLE CLAIM_DWD.DWD_API_MONITOR_RESULT (
    app_name VARCHAR(255) COMMENT '项目名',
    request_uri VARCHAR(255) comment '请求连接',
    request_time DATE comment '请求时间',
    num INT comment '请求次数',
    error_num INT comment '错误次数',
    error_rate DECIMAL(10, 4) comment '错误率',
    avg_time DECIMAL(10, 0) comment '平均响应时长（ms）',
    time_taken_99 VARCHAR(255)  comment '99线（ms）',
    time_taken_95 VARCHAR(255) comment '95线（ms）'
)ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='API接口监控表';





drop table if exists CLAIM_DWD.DWD_YSJ_COST_STATISTICS;







drop table if exists CLAIM_DWD.DWD_YSJ_LR_COST_STATISTICS;


CREATE TABLE CLAIM_DWD.DWD_YSJ_LR_COST_STATISTICS (
    channel VARCHAR(50)  COMMENT '渠道',
    data_dt VARCHAR(10)  COMMENT '日期',
    kt_num bigint  COMMENT '快瞳电子票调用次数',
    kt_cost DECIMAL(10, 2)  COMMENT '快瞳费用',
    ocr_num bigint  COMMENT 'ocr调用次数',
    ocr_cost DECIMAL(10, 2)  COMMENT 'ocr调用费用',
    hsbx_y_num bigint  COMMENT '海盛宝信电子票无明细调用次数',
    hsbx_y_cost DECIMAL(10, 2)  COMMENT '海盛宝信无明细费用',
    hsbx_n_num bigint  COMMENT '海盛宝信电子票有明细调用次数',
    hsbx_n_cost DECIMAL(10, 2)  COMMENT '海盛宝信有明细费用',
    inp bigint  COMMENT '录入次数',
    inp_cost DECIMAL(10, 2)  COMMENT '录入费用',
    rev bigint  COMMENT '复核次数',
    rev_cost DECIMAL(10, 2)  COMMENT '复核费用',
    wsy_num bigint  COMMENT '五要素操作次数',
    wsy_cost DECIMAL(10, 2)  COMMENT '五要素操作费用'
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='因朔桔成本数据表';







drop table if exists CLAIM_DWD.DWD_YSJ_INPUT_FEE_COUNT;


CREATE TABLE CLAIM_DWD.DWD_YSJ_INPUT_FEE_COUNT (
    channel VARCHAR(50)  COMMENT '渠道',
    data_dt VARCHAR(10)  COMMENT '日期',
    kt_cost DECIMAL(10, 2)  COMMENT '快瞳费用',
    ocr_cost DECIMAL(10, 2)  COMMENT 'ocr调用费用',
    hsbx_y_cost DECIMAL(10, 2)  COMMENT '海盛宝信无明细费用',
    hsbx_n_cost DECIMAL(10, 2)  COMMENT '海盛宝信有明细费用',
    inp_cost DECIMAL(10, 2)  COMMENT '录入费用',
    rev_cost DECIMAL(10, 2)  COMMENT '复核费用',
    wsy_cost DECIMAL(10, 2)  COMMENT '五要素操作费用'
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='因朔桔成本数据表';


drop table if exists CLAIM_DWD.DWD_YH_CLAIM_DAY;

CREATE TABLE CLAIM_DWD.DWD_YH_CLAIM_DAY (
     data_dt VARCHAR(10)  COMMENT '日期' ,
    JJL INT COMMENT '进件量',
    claim_cnt INT COMMENT '理赔数量',
    pay_amt DECIMAL(10, 2) COMMENT '赔付金额',
    in_pay_amt DECIMAL(10, 2)  COMMENT '政策内赔付金额',
    out_pay_amt DECIMAL(10, 2) COMMENT '政策外赔付金额'
)  ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COMMENT='湖南医惠保理赔';




CREATE TABLE `CLAIM_DWD`.`DWD_CP11_TOTAL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(10) NOT NULL COMMENT '账期',
  `CLAIM_VOL` bigint  NOT NULL COMMENT '案件量',
  `PRICE_DJ` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `FEE` DECIMAL(10,2) NOT NULL COMMENT '费用小计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
)
COMMENT='太保高端医疗账单汇总表'
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;






drop table if exists CLAIM_DWD.DWD_CS01_TOTAL;


CREATE TABLE `CLAIM_DWD`.`DWD_CS01_TOTAL` (
  `INSURE_COMPANY_CHANNEL` VARCHAR(50) NOT NULL COMMENT '渠道',
  `YEAR_MONTH` VARCHAR(10) NOT NULL COMMENT '账期',
#     claim_source VARCHAR(10) COMMENT '来源',
  `CLAIM_VOL` bigint  NOT NULL COMMENT '案件量',
  `PRICE_DJ` DECIMAL(10,2) NOT NULL COMMENT '单价',
  `FEE` DECIMAL(10,2) NOT NULL COMMENT '费用小计',
  `DATA_DT` VARCHAR(10) NOT NULL COMMENT '调度日期'
)
COMMENT='长生人寿账单汇总表'
ENGINE=InnoDB
DEFAULT CHARSET=utf8mb4;